language: python

python:
    - 2.7

install:
  - pip install -r requirements.txt
  - pip install .

script:
  - cd test/unit
  # testing eos getters
  - nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_bgp_config
  - nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_bgp_neighbors
  # not implemented on eos
  # - nosetests -v TestEOSDriver:TestGetterEOSDriver.test_bgp_neighbors_detail
  - nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_environment
  - nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_facts
  - nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_interfaces
  - nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_interfaces_counters
  - nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_lldp_neighbors
  - nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_lldp_neighbors_detail
  - nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_arp_table
  - nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_ntp_peers
  - nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_interfaces_ip
  - nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_mac_address_table
  - nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_route_to
  - nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_snmp_information
